[licenses]
version = 2
allow = [ "Apache-2.0", "MPL-2.0", "Unicode-DFS-2016", "MIT" ]
confidence-threshold = 0.8
exceptions = []

[advisories]
version = 2
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]